#!/usr/bin/env python3
"""
build_wiki_graph.py — generate an interactive D3 knowledge graph of the wiki.

Usage: build_wiki_graph.py OUT_DIR SUBWIKI1 SUBWIKI2 ...

Writes OUT_DIR/graph.html: a self-contained page (D3 inlined) with one node
per wiki page and one edge per [[wikilink]] between pages. Features: force
layout, zoom/drag, per-sub-wiki color legend with toggles, page-type filter,
search, hover-to-highlight neighbors, click to open the rendered page.

The Evolution view (topic trends over time: percentage or count of papers
per year carrying selected tags, click a point to list those papers) also
follows ISMIR25Viz; the year comes from the section slug or citation line.

The Authors view (author-topic bipartite, co-authorship, and topic
co-occurrence networks with min-count sliders) follows ISMIR25Viz from
"Beyond a Western Center of MIR" (https://transactions.ismir.net/articles/10.5334/tismir.265).
Authors come from each paper section's citation line; topics are the
section's Tags minus ROLE_TAGS.

Modeled on the Music 423 knowledge graph (https://ccrma.stanford.edu/~jos/wiki-graph-423gl.html),
generated by _convert.py in the music423-2023 course repo.

Node rules:
  - Every <subwiki>/**/*.md becomes a node, except index.md, log.md, SCHEMA.md.
  - Node type comes from the `type:` frontmatter field (concept, entity, ...).
  - Any file named source-papers.md is additionally split into one node per
    `### heading` section (type "source"), so inbound links of the form
    [[entities/source-papers#paper-slug]] land on the individual paper.
    Wikilinks inside a section are attributed to that section's node.

Wikilinks are resolved with the same rules as build_wiki.py (bare name,
subdir/name, subwiki/path/name, #anchor). Links inside code spans are ignored.
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_wiki import (  # noqa: E402
    WIKILINK_RE, collect_md_files, resolve_wikilink_target, split_protecting_code,
    extract_title,
)

SKIP_STEMS = {"index", "log", "SCHEMA"}
SPLIT_STEMS = {"source-papers"}
SECTION_RE = re.compile(r"^### +(.+?)\s*$", re.MULTILINE)
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)

# Tableau-20 style palette, one color per sub-wiki
PALETTE = [
    "#4e79a7", "#f28e2b", "#e15759", "#76b7b2", "#59a14f",
    "#edc948", "#b07aa1", "#ff9da7", "#9c755f", "#bab0ac",
    "#86bcb6", "#8cd17d", "#b6992d", "#499894", "#d37295",
    "#a0cbe8", "#ffbe7d", "#d4a6c8", "#fabfd2", "#d7b5a6",
]


# Site-specific chrome for the shared graph.html template (kept byte-identical
# with music423-2023/wiki/graph.html; everything that differs lives here).
SITE = {
    "title": "JOS LLM Wiki — Knowledge Graph",
    "home_label": "JOS LLM Wiki",
    "home_href": "index.html",
    "group_label": "Sub-wikis",
    "click_hint": "Click to open page",
    "evolution_bin": 5,   # corpus spans 1953-2026 with many single-paper years
    "min_papers": 2,      # default Authors-view threshold
    "credit_html": (
        'Modeled on the <a href="https://ccrma.stanford.edu/~jos/wiki-graph-423gl.html">'
        'Music 423 knowledge graph</a>; author and evolution networks after '
        '<a href="https://transactions.ismir.net/articles/10.5334/tismir.265">ISMIR25Viz</a>.'
    ),
}


def slugify(heading: str) -> str:
    """Approximate pandoc's auto-identifier for a heading."""
    s = heading.strip().lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s]+", "-", s)
    return s.strip("-")


def frontmatter_field(content: str, key: str) -> str:
    m = FRONTMATTER_RE.match(content)
    if not m:
        return ""
    for line in m.group(1).splitlines():
        if line.startswith(f"{key}:"):
            return line.split(":", 1)[1].strip()
    return ""


def page_type(content: str) -> str:
    raw = frontmatter_field(content, "type")
    # Template pages declare "entity | concept | ..." — take the first.
    first = raw.split("|")[0].strip().strip('"').strip("'")
    return first or "page"


def page_tags(content: str) -> list[str]:
    raw = frontmatter_field(content, "tags")
    m = re.match(r"\[(.*)\]", raw)
    if not m:
        return []
    return [t.strip().strip("'\"") for t in m.group(1).split(",") if t.strip()]


def split_sections(content: str) -> tuple[str, list[tuple[str, str, str]]]:
    """Return (preamble, [(slug, heading_text, body), ...]) for ### sections."""
    matches = list(SECTION_RE.finditer(content))
    if not matches:
        return content, []
    preamble = content[: matches[0].start()]
    sections = []
    for i, m in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        heading = m.group(1).strip()
        sections.append((slugify(heading), heading, content[m.end():end]))
    return preamble, sections


CITATION_RE = re.compile(r'^\*\*[“"].*?[”"]\*\*\s*(?:-{1,2}|—|–)\s*(.*)$', re.MULTILINE)
TAGS_LINE_RE = re.compile(r"^- Tags:\s*(.+)$", re.MULTILINE)
ET_AL_RE = re.compile(r"\s+et\s+al\.?", re.IGNORECASE)


def parse_authors(section_body: str) -> list[str]:
    """Author names from a paper section's citation line.

    The citation line looks like
        **"Title"** - A. Author, B. Author (Affiliation) · Venue · ...
    Names run from the dash after the title to the first ' · '. Parenthesized
    affiliations are dropped; names split on ',', '&' and ' and '; a trailing
    'et al.' is removed. Returns [] when the section has no citation line.
    """
    m = CITATION_RE.search(section_body)
    if not m:
        return []
    names = re.sub(r"\([^)]*\)", "", m.group(1))   # affiliations (may contain dashes)
    # Names end at the first separator: ' · ', ' - ', ' -- ', ' — ' or ' – '
    names = re.split(r"\s+(?:·|-{1,2}|—|–)\s+", names)[0]
    names = ET_AL_RE.sub("", names)
    names = names.replace("*", "")
    out = []
    for part in re.split(r",|&|\band\b", names):
        name = re.sub(r"\s+", " ", part).strip(" .;:")
        if name and len(name) < 60:
            out.append(name)
    return out


# Tags that describe a source's role rather than its subject; excluded from
# the author/topic network (still present in each node's `tags` for search).
ROLE_TAGS = {"reference", "comparison", "tutorial", "person", "meta", "index",
             "log", "overview"}


SLUG_YEAR_RE = re.compile(r"-((?:19|20)\d\d)$")
YEAR_RE = re.compile(r"\b(19[5-9]\d|20[0-3]\d)\b")


def parse_year(slug: str, section_body: str) -> int | None:
    """Publication year: trailing year in the section slug, else the first
    year mentioned in the citation line after the title. None if neither."""
    m = SLUG_YEAR_RE.search(slug)
    if m:
        return int(m.group(1))
    m = CITATION_RE.search(section_body)
    if m:
        y = YEAR_RE.search(m.group(1))
        if y:
            return int(y.group(1))
    return None


def parse_section_tags(section_body: str) -> list[str]:
    """Tags from the '- Tags: a, b, c' line of a paper section."""
    m = TAGS_LINE_RE.search(section_body)
    if not m:
        return []
    return [t.strip().strip("'\"`") for t in m.group(1).split(",") if t.strip()]


def author_key(name: str) -> str:
    """Identity key for an author name: accents, case, hyphens and punctuation folded.

    Middle initials are NOT folded (that would merge e.g. Sang-gil Lee and Sang-Hoon Lee).
    """
    import unicodedata
    k = unicodedata.normalize("NFKD", name)
    k = "".join(c for c in k if not unicodedata.combining(c))
    k = k.replace("ł", "l").replace("Ł", "L").replace("ø", "o").replace("Ø", "O").replace("ß", "ss")
    return re.sub(r"[^a-z ]", "", k.lower().replace("-", " ")).strip()


def canonicalize_authors(nodes: list[dict]) -> int:
    """Give every spelling variant of an author one display form, in place.

    Variants share an author_key(). The display form is the variant with the most
    non-ASCII characters (the accented spelling is the accurate one), then the most
    frequent. Also removes repeated names within a node. Returns the number of
    author keys that had more than one spelling.
    """
    from collections import Counter, defaultdict
    forms: dict[str, Counter] = defaultdict(Counter)
    for n in nodes:
        for a in n.get("authors", []):
            forms[author_key(a)][a] += 1
    display = {k: max(c, key=lambda f: (sum(ord(ch) > 127 for ch in f), c[f], f))
               for k, c in forms.items()}
    for n in nodes:
        seen: set[str] = set()
        out: list[str] = []
        for a in n.get("authors", []):
            k = author_key(a)
            if k and k not in seen:
                seen.add(k)
                out.append(display[k])
        n["authors"] = out
    return sum(1 for c in forms.values() if len(c) > 1)


def wikilinks_in(text: str) -> list[str]:
    """Wikilink targets (without |display) in text, ignoring code spans."""
    out = []
    for is_code, chunk in split_protecting_code(text):
        if is_code:
            continue
        for m in WIKILINK_RE.finditer(chunk):
            inner = m.group(1)
            out.append(inner.split("|", 1)[0])
    return out


def build_graph(out_dir: Path, subwikis: list[str]) -> dict:
    by_bare, by_relpath = collect_md_files(out_dir, subwikis)

    nodes: dict[str, dict] = {}
    # (md Path, anchor) -> node id, so resolved links map back to nodes
    node_key: dict[tuple[Path, str], str] = {}
    # Deferred edge sources: (source node id, source md, [targets])
    pending: list[tuple[str, Path, list[str]]] = []

    def add_node(md: Path, anchor: str, ntype: str, title: str, tags: list[str],
                 authors: list[str] | None = None, year: int | None = None) -> str:
        rel = md.relative_to(out_dir)
        sw = rel.parts[0]
        bare = md.stem if not anchor else anchor
        nid = f"{rel.with_suffix('')}" + (f"#{anchor}" if anchor else "")
        href = str(rel.with_suffix(".html")) + (f"#{anchor}" if anchor else "")
        nodes[nid] = {
            "id": nid, "bare": bare, "topic": sw, "type": ntype,
            "href": href, "title": title, "tags": tags,
            "authors": authors or [],
            "year": year,
            "links_out": 0, "links_in": 0,
        }
        node_key[(md, anchor)] = nid
        return nid

    for sw in subwikis:
        sw_dir = out_dir / sw
        if not sw_dir.is_dir():
            continue
        for md in sorted(sw_dir.rglob("*.md")):
            if md.stem in SKIP_STEMS:
                continue
            content = md.read_text()
            title = extract_title(content) or md.stem
            tags = page_tags(content)
            page_id = add_node(md, "", page_type(content), title, tags)
            if md.stem in SPLIT_STEMS:
                preamble, sections = split_sections(content)
                pending.append((page_id, md, wikilinks_in(preamble)))
                for slug, heading, body in sections:
                    sid = add_node(md, slug, "source", heading,
                                   parse_section_tags(body), parse_authors(body),
                                   parse_year(slug, body))
                    pending.append((sid, md, wikilinks_in(body)))
            else:
                pending.append((page_id, md, wikilinks_in(content)))

    edges: list[dict] = []
    seen: set[tuple[str, str]] = set()
    for src_id, src_md, targets in pending:
        for target in targets:
            dst, anchor = resolve_wikilink_target(target, src_md, out_dir, by_bare, by_relpath)
            if dst is None:
                continue  # broken links are reported by build_wiki.py
            dst_id = node_key.get((dst, anchor)) or node_key.get((dst, ""))
            if dst_id is None or dst_id == src_id:
                continue
            key = (src_id, dst_id)
            if key in seen:
                continue
            seen.add(key)
            edges.append({"source": src_id, "target": dst_id})
            nodes[src_id]["links_out"] += 1
            nodes[dst_id]["links_in"] += 1

    canonicalize_authors(list(nodes.values()))

    topics = [sw for sw in subwikis if (out_dir / sw).is_dir()]
    topic_colors = {t: PALETTE[i % len(PALETTE)] for i, t in enumerate(topics)}
    types = sorted({n["type"] for n in nodes.values()})
    return {
        "nodes": list(nodes.values()),
        "edges": edges,
        "topics": topics,
        "topic_colors": topic_colors,
        "types": types,
        "role_tags": sorted(ROLE_TAGS),
        "site": SITE,
    }


def render(graph: dict, out_path: Path) -> None:
    script_dir = Path(__file__).resolve().parent
    template = script_dir / "graph.html"
    d3 = script_dir / "d3.v7.min.js"
    for f in (template, d3):
        if not f.is_file():
            print(f"*** missing {f}", file=sys.stderr)
            sys.exit(1)
    html = template.read_text()
    if '"GRAPH_DATA_PLACEHOLDER"' not in html or "<!--D3_INLINE-->" not in html:
        print(f"*** {template} lacks the data/D3 placeholders", file=sys.stderr)
        sys.exit(1)
    html = html.replace('"GRAPH_DATA_PLACEHOLDER"', json.dumps(graph))
    html = html.replace("<!--D3_INLINE-->", f"<script>{d3.read_text()}</script>")
    out_path.write_text(html)


def main() -> None:
    if len(sys.argv) < 3:
        print("Usage: build_wiki_graph.py OUT_DIR SUBWIKI1 [SUBWIKI2 ...]", file=sys.stderr)
        sys.exit(1)
    out_dir = Path(sys.argv[1]).resolve()
    subwikis = sys.argv[2:]
    if not out_dir.is_dir():
        print(f"*** {out_dir} does not exist", file=sys.stderr)
        sys.exit(1)
    graph = build_graph(out_dir, subwikis)
    out_path = out_dir / "graph.html"
    render(graph, out_path)
    n_src = sum(1 for n in graph["nodes"] if n["type"] == "source")
    print(f"  graph: {len(graph['nodes'])} nodes ({n_src} per-paper source nodes), "
          f"{len(graph['edges'])} edges, {len(graph['topics'])} sub-wikis -> {out_path}")


if __name__ == "__main__":
    main()
